"""Inclusão coluna ID_TRANSACAO_BANCARIA

Revision ID: 39242d7653ad
Revises: 485a674ca447
Create Date: 2026-08-14 12:27:12.127574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39242d7653ad'
down_revision: Union[str, Sequence[str], None] = '485a674ca447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_transacao_bancaria', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.drop_column('id_transacao_bancaria')

    # ### end Alembic commands ###
